variables:
- group: nuget

trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    include:
    - Packages/Archivist/Scribe.csproj

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:yyyyMMdd)$(Rev:-r)
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: '--filter Category=UnitTests'
    publishTestResults: true
    testRunTitle: $(Build.SourceVersionMessage)
    workingDirectory: $(Build.Repository.LocalPath)/Packages/Scribe.Tests
  displayName: 'Run Tests'
- script: docker build -f release.dockerfile --build-arg API_KEY=$(API_KEY) .
  workingDirectory: $(Build.Repository.LocalPath)/Packages/Scribe
  displayName: 'Pack and push to Nuget'